name: Java CI with Maven

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check setup
        run: |
          java --version
          ls -ltr

      - name: OSS scan
        run: mvn ossindex:audit
        continue-on-error: true

      - name: OWASP scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check
        
      - name: Build code and create docker images
        run: mvn clean install docker:build

      - name : Re tag the docker image
        run: docker tag  dnyanyog.org/patient-service:latest vaish864/patient-service:latest

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
         username: ${{secrets.DOCKER_REGISTRY_USER}}
         password: ${{secrets.DOCKER_REGISTRY_PAT}}
   
      - name: Push docker images
        run: docker push "${{ secrets.CONTAINER_REGISTRY_URL }}/patient-service:latest"
